var placesToVisit = ["Paris", "Tokyo", "New York", "Rome", "Sydney"];
console.log("Original Order:");
console.log(placesToVisit);
var alphabeticalOrder = placesToVisit.slice().sort();
console.log("\nAlphabetical Order (without modifying original list):");
console.log(alphabeticalOrder);
console.log("Original Order (unchanged):");
console.log(placesToVisit);
var reverseAlphabeticalOrder = placesToVisit.slice().sort().reverse();
console.log("\nReverse Alphabetical Order (without modifying original list):");
console.log(reverseAlphabeticalOrder);
console.log("Original Order (unchanged):");
console.log(placesToVisit);
placesToVisit.reverse();
console.log("\nReversed Order:");
console.log(placesToVisit);
placesToVisit.reverse();
console.log("\nOriginal Order (after reversing twice):");
console.log(placesToVisit);
placesToVisit.sort();
console.log("\nAlphabetical Order (after sorting):");
console.log(placesToVisit);
placesToVisit.sort().reverse();
console.log("\nReverse Alphabetical Order (after sorting in reverse):");
console.log(placesToVisit);
